[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/public/app.js"
[build]
  publish = "public/app.js"
  functions = "netlify/functions"
  command = "npm install"


